apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: dummy-prueba-ace-01
  namespace: ace-apidb-dev
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace-apidb-dev/dummy-prueba-ace
  configurations: []
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-C9NCDM
    use: AppConnectEnterpriseNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.4.0-r1